// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGRGyCrovYwM3e19eqy_qfKdzv71_puzY',
    appId: '1:1095527512131:web:2a71d7338759b5b02dfcf6',
    messagingSenderId: '1095527512131',
    projectId: 'keep-d22f7',
    authDomain: 'keep-d22f7.firebaseapp.com',
    storageBucket: 'keep-d22f7.firebasestorage.app',
    measurementId: 'G-TJHXT4GWSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAms0lxhhAN9T_MpVUZPOiKTM6J7fH5Q98',
    appId: '1:1095527512131:android:d9c8ae0e3d0e7ffa2dfcf6',
    messagingSenderId: '1095527512131',
    projectId: 'keep-d22f7',
    storageBucket: 'keep-d22f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv-tCspQp4iiMlphFpB4t8kzTW7j1Y920',
    appId: '1:1095527512131:ios:b130da40659888172dfcf6',
    messagingSenderId: '1095527512131',
    projectId: 'keep-d22f7',
    storageBucket: 'keep-d22f7.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv-tCspQp4iiMlphFpB4t8kzTW7j1Y920',
    appId: '1:1095527512131:ios:b130da40659888172dfcf6',
    messagingSenderId: '1095527512131',
    projectId: 'keep-d22f7',
    storageBucket: 'keep-d22f7.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGRGyCrovYwM3e19eqy_qfKdzv71_puzY',
    appId: '1:1095527512131:web:0de24a5c83ade71a2dfcf6',
    messagingSenderId: '1095527512131',
    projectId: 'keep-d22f7',
    authDomain: 'keep-d22f7.firebaseapp.com',
    storageBucket: 'keep-d22f7.firebasestorage.app',
    measurementId: 'G-HJXC419LR2',
  );
}
